import sys
from _typeshed import (  # All type variable use in this module requires comparability.
    SupportsRichComparison,
    SupportsRichComparisonT as _T,
)
from typing import Final

__about__: Final[str]

def heapify(heap: list[SupportsRichComparison], /) -> None: ...
def heappop(heap: list[_T], /) -> _T: ...
def heappush(heap: list[_T], item: _T, /) -> None: ...
def heappushpop(heap: list[_T], item: _T, /) -> _T: ...
def heapreplace(heap: list[_T], item: _T, /) -> _T: ...

if sys.version_info >= (3, 14):
    def heapify_max(heap: list[SupportsRichComparison], /) -> None: ...
    def heappop_max(heap: list[_T], /) -> _T: ...
    def heappush_max(heap: list[_T], item: _T, /) -> None: ...
    def heappushpop_max(heap: list[_T], item: _T, /) -> _T: ...
    def heapreplace_max(heap: list[_T], item: _T, /) -> _T: ...

else:
    def _heapify_max(heap: list[SupportsRichComparison]) -> None: ...  # undocumented
    def _heappop_max(heap: list[_T], /) -> _T: ...  # undocumented
    def _heapreplace_max(heap: list[_T], item: _T, /) -> _T: ...  # undocumented
